<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>conditor</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Conditor.Core/Conditor.Core.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
